version: "3.9"

# Default network for the containers
networks:
  nextchat:
    name: nextchat
    driver: bridge

services:
  # Main service without proxy
  chatgpt-next-web:
    profiles: [ "no-proxy" ]
    container_name: chatgpt-next-web
    image: yidadaa/chatgpt-next-web
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY
      - CODE
      - BASE_URL
      - OPENAI_ORG_ID
      - HIDE_USER_API_KEY
      - DISABLE_GPT4
      - ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK
      - GOOGLE_API_KEY
      - PROXY_URL
    networks:
      - nextchat

  # Service with proxy support
  chatgpt-next-web-proxy:
    profiles: [ "proxy" ]
    container_name: chatgpt-next-web-proxy
    image: yidadaa/chatgpt-next-web
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY
      - CODE
      - BASE_URL
      - OPENAI_ORG_ID
      - HIDE_USER_API_KEY
      - DISABLE_GPT4
      - ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK
      - GOOGLE_API_KEY
      - PROXY_URL
    networks:
      - nextchat
